# Generated by Django 2.0.5 on 2018-09-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city1', models.CharField(max_length=250)),
                ('city2', models.CharField(max_length=250)),
                ('pub_date', models.DateTimeField(verbose_name='date searched')),
            ],
        ),
    ]
