# Generated by Django 2.0.5 on 2018-09-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='logs',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='date searched'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='city1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='logs',
            name='city2',
            field=models.CharField(max_length=100),
        ),
    ]
